# Generated by Django 5.2.4 on 2025-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bankaccount_updated_at_cartitem_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlaskListAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
