# Generated by Django 5.2.4 on 2025-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_slug_alter_category_name_alter_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-09-12'),
            preserve_default=False,
        ),
    ]
