# Generated by Django 5.2.4 on 2025-09-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_color_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_pending_email',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
