# Generated by Django 5.2.4 on 2025-09-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
