# Generated by Django 5.2.4 on 2025-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='srcURL',
            field=models.URLField(blank=True),
        ),
    ]
