# Generated by Django 5.2.4 on 2025-09-21 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_srcurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Discount percentage (0–70).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
