# Generated by Django 5.2.4 on 2025-09-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.CharField(blank=True),
        ),
    ]
