# Generated by Django 5.2.4 on 2025-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_cartitem_customer_remove_cartitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
