# Generated by Django 5.2.4 on 2025-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_bankaccount_bank_code_bankaccount_subaccount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='subaccount_id',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='subaccount_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
