# Generated by Django 5.2.4 on 2025-09-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_bankaccount_subaccount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
