# Generated by Django 5.2.4 on 2025-09-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='reference',
        ),
    ]
